server:
  port: 9081
  servlet:
    context-path: /auth
spring:
  redis:
    database: 0
    host: 192.168.240.210
    lettuce:
      pool:
        max-active: 8
        max-idle: 10
        max-wait: 1ms
        min-idle: 5
      shutdown-timeout: 100ms
    port: 6379
